# Generated by Django 5.2.4 on 2025-08-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedfile',
            name='case_id',
        ),
    ]
