# Generated by Django 5.2.3 on 2025-08-05 13:28

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_submittedfile_case_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='extracted_file')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted by UniversalTextExtractor')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if extraction fails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_file', to='api.submittedfile')),
            ],
            options={
                'verbose_name': 'Extracted File',
                'verbose_name_plural': 'Extracted Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
