# Generated by Django 5.2.3 on 2025-08-05 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_extractedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted by the universal extractor')),
                ('extracted_metadata', models.JSONField(default=dict, help_text='Metadata from universal extractor (e.g., pages, images processed)')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('submitted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_file', to='api.submittedfile')),
            ],
            options={
                'verbose_name': 'Processed File',
                'verbose_name_plural': 'Processed Files',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExtractedFile',
        ),
    ]
