# Generated by Django 5.2.4 on 2025-08-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_processedfile_delete_extractedfile'),
    ]

    operations = [
        # Delete models that are no longer needed
        migrations.DeleteModel(
            name='ProcessedFile',
        ),
        migrations.DeleteModel(
            name='MLReferenceFile',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
