# Generated by Django 5.2.4 on 2025-08-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250814_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedfile',
            name='final_category',
        ),
        migrations.RemoveField(
            model_name='submittedfile',
            name='match',
        ),
        migrations.AddField(
            model_name='categoryschema',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submittedfile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_files', to='api.categoryschema'),
        ),
    ]
