# Generated by Django 5.2.4 on 2025-08-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_submittedfile_final_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedfile',
            name='ai_response',
            field=models.TextField(blank=True, help_text='AI-generated response to the query'),
        ),
        migrations.AddField(
            model_name='submittedfile',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Full extracted text from the document'),
        ),
        migrations.AddField(
            model_name='submittedfile',
            name='processing_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Processing metadata like chunks, retrieval method, evaluation scores'),
        ),
        migrations.AddField(
            model_name='submittedfile',
            name='query',
            field=models.TextField(blank=True, help_text='User query about the document'),
        ),
    ]
