# Generated by Django 5.2.4 on 2025-08-16 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_submittedfile_ai_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedfile',
            name='extracted_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(help_text='Celery task ID', max_length=255, unique=True)),
                ('task_type', models.CharField(default='document_processing', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('query', models.TextField()),
                ('method', models.CharField(default='hybrid', max_length=20)),
                ('top_k', models.IntegerField(default=30)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoryschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Task',
                'verbose_name_plural': 'Processing Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
