# Generated by Django 5.2.4 on 2025-08-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_submittedfile_extracted_fields_processingtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingtask',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True),
        ),
    ]
